name: CI
on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: kubectl
        run: kubectl get pods -A
      - uses: actions/checkout@v4
      - name: check ls
        run: ls -la
      - name: apply yamls to minikube # except pool address
        run: find python/yamls/ -type f -name '*.yaml' ! -name 'metallelb-pool.yaml' -exec kubectl apply -f {} \;
      - name: tests for endpoints
        run: |
          curl app.python.com:8000/results
          curl app.python.com:8000/csv
          curl app.python.com:8000/healthcheck
        
 

