name: CI
on:
  push
jobs:
  job1:
     runs-on: ubuntu-latest
     name: job1
     steps:
       - uses: medyagh/setup-minikube@latest
       - uses: actions/checkout@v4
       - name: start minikube
         id: minikube
       #now you can run kubectl to see the pods in the cluster
       - name: kubectl
         run: kubectl get pods -A
       - name: checkout code
       - name: check ls
         run: ls -la
       - name: apply yamls to minikube
         run: kubectl apply -f python/yamls/. --validate=false


