name: CI
on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: kubectl
        run: kubectl get pods -A
      - uses: actions/checkout@v4
      - name: check ls
        run: ls -la
      - name: apply helm chart
        run: helm install python-app -f python/helm/python-app/values.yaml python/helm/python-app/.
      - name: sleep 40s
        run: sleep 40s
      - name: check pods for service
        run: kubectl get po
      - name: run endpoints tests
        run: |
          curl $(minikube service python-service --url)/results
          curl $(minikube service python-service --url)/csv
          curl $(minikube service python-service --url)/healthcheck
        
 

